In [14]:
import time
import stretch_body.robot
import numpy as np
from stretch_body.hello_utils import ThreadServiceExit

In [106]:
robot=stretch_body.robot.Robot()
robot.startup()

True

In [77]:
import open3d as o3d
pcd = o3d.io.read_point_cloud("/home/hello-robot/Documents/shaving_code-main/2022-05-27.ply")
pcd_select = o3d.io.read_point_cloud("/home/hello-robot/Documents/shaving_code-main/2022-05-27-selected.ply")

#Selected Points Visualization
pcd = pcd.voxel_down_sample(voxel_size=0.035)
pcd_select.paint_uniform_color([1, 0, 0])
#foundpcl = foundpcl.voxel_down_sample(voxel_size=0.025)
o3d.visualization.draw_geometries([pcd,pcd_select])

In [90]:
sel = np.asarray(pcd_select.points)
print(sel)
print("sorted by x position")
selsort = np.sort(sel,axis=0)
print(np.sort(sel,axis=0))

[[-0.05665165 -0.15315214 -1.45853247]
 [ 0.11154653 -0.1450643  -1.44658673]
 [ 0.07704861 -0.14517879 -1.4443972 ]
 [ 0.04151017 -0.14437921 -1.44896465]
 [-0.09887614 -0.14483041 -1.44918687]
 [-0.16936556 -0.14412702 -1.46133163]
 [ 0.14666707 -0.14454011 -1.448355  ]
 [-0.0684549  -0.14148999 -1.45046617]
 [-0.13339232 -0.14154472 -1.45144737]
 [-0.02670315 -0.13792218 -1.44898039]
 [ 0.00642124 -0.14345498 -1.44811351]]
sorted by x position
[[-0.16936556 -0.15315214 -1.46133163]
 [-0.13339232 -0.14517879 -1.45853247]
 [-0.09887614 -0.1450643  -1.45144737]
 [-0.0684549  -0.14483041 -1.45046617]
 [-0.05665165 -0.14454011 -1.44918687]
 [-0.02670315 -0.14437921 -1.44898039]
 [ 0.00642124 -0.14412702 -1.44896465]
 [ 0.04151017 -0.14345498 -1.448355  ]
 [ 0.07704861 -0.14154472 -1.44811351]
 [ 0.11154653 -0.14148999 -1.44658673]
 [ 0.14666707 -0.13792218 -1.4443972 ]]


In [127]:
#Calculated height w/ ref to bot (largeish margin of error) : 2 (.1 meter added to avoid collisiion w/ wrist)
prev_base_pos = selsort[0][0]
for point in selsort:
    base_adjust=point[0]-prev_base_pos

    robot.base.translate_by(base_adjust)
    robot.push_command()
    time.sleep(3)

    robot.lift.move_to(2.35+point[2])
    robot.push_command()
    
    prev_base_pos=point[0]
    time.sleep(3)

In [128]:
print("arm status: " + str(robot.arm.status['pos']))
print("lift status: " + str(robot.lift.status['pos']))
print("wrist roll status: " + str(robot.end_of_arm.status['wrist_roll']['pos']))
print("wrist pitch status: " + str(robot.end_of_arm.status['wrist_pitch']['pos']))
print("wrist yaw status: " + str(robot.end_of_arm.status['wrist_yaw']['pos']))

arm status: 0.2617865698672953
lift status: 0.905603380189536
wrist roll status: -0.056757289151768725
wrist pitch status: -0.32673790781964157
wrist yaw status: 1.668843265487254


In [105]:
robot.stop()


In [97]:
prev_base_pos = selsort[0][0]
for point in selsort:
    base_adjust=point[0]-prev_base_pos
    print(base_adjust)

0.0
0.035973233754028056
0.07048941874871174
0.1009106591299678
0.11271390417439708
0.1426624022008804
0.1757867963981247
0.2108757253143682
0.2464141621972154
0.2809120852040816
0.3160326211224491


In [126]:
robot.end_of_arm.move_by('wrist_pitch',0.1)